version: "3.5"

services:

  currency-db:
    restart: always
    build:
      context: .
      args:
        - SSH_ROOT_USER=root
        - SSH_ROOT_PASSWORD=passw0rd
    image: postgres:ucc
    container_name: ucc_db
    environment:
      - SSH_USER=sshu
      - SSH_PASS=passw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_USER=ucc
      - DB_PASSWORD=passw0rd
      - DB_NAME=uccdb
      - DB_SCHEMA=ucc_cfg
      - DB_TABLESPACE=ucc_cfg_data
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
      - 2223:22