#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username ${POSTGRES_USER} --dbname ${POSTGRES_USER} <<-EOSQL
    CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASSWORD}' VALID UNTIL '2100-03-17';
    CREATE TABLESPACE ${DB_TABLESPACE} OWNER ${DB_USER} LOCATION '/var/lib/postgresql/data';
    CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER} ENCODING = 'UTF8' TABLESPACE = ${DB_TABLESPACE} CONNECTION LIMIT = -1;
EOSQL

psql -v ON_ERROR_STOP=1 --username ${DB_USER} --dbname ${DB_NAME} <<-EOSQL
    CREATE SCHEMA ${DB_SCHEMA} AUTHORIZATION ${DB_USER};
    ALTER ROLE ${DB_USER} SET search_path = ${DB_SCHEMA},public;
EOSQL

